---
- name: Up Open5GS server
  hosts: localhost
  connection: local
  become: yes

  vars:
    open5gs_ip: "127.0.0.1"
    ip_range: "{{ range(26, 36) | map('string') | list }}"
    base_ip: "172.31.0"
    # Corrigido a forma de pegar a variável de ambiente
    interface: "{{ lookup('env', 'CORE_INTERFACE') | default('ens3') }}"
    essential_packages:
      - unzip

  tasks:
    - name: Registrar status de comissionamento
      ansible.builtin.shell: |
        echo "$(date '+%Y-%m-%d %H:%M:%S') - Comissionamento CORE Open5GS Iniciado" >> /home/lance/registros.txt

    - name: Limpar arquivos de repositório do Docker com erro
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/docker.sources
        - /etc/apt/sources.list.d/docker-repo.list

    - name: Forçar atualização do cache do apt após limpeza
      become: yes
      apt:
        update_cache: yes

    - name: Instalar dependências iniciais
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Adicionar meu usuário ao grupo docker
      user:
        name: "lance"
        groups: docker
        append: yes

    - name: Criar rede macvlan_net via Shell (Garante estabilidade)
      shell: >
        docker network create -d macvlan
        --subnet=172.31.0.0/24
        --gateway=172.31.0.1
        -o parent=ens3
        macvlan_net
      become: yes
      ignore_errors: yes


    - name: Subir o ambiente Docker Compose com Macvlan
      community.docker.docker_compose_v2:
        project_src: "/home/lance/ansible/pacote_B/docker"
        files:
          - docker-compose-5gc-macvlan.yml
        state: present
        wait: yes


    - name: Registrar status de comissionamento final
      ansible.builtin.shell: |
        echo "$(date '+%Y-%m-%d %H:%M:%S') - Comissionamento CORE Open5GS Finalizado com IP {{ ansible_facts[interface]['ipv4']['address'] | default(ansible_default_ipv4.address) }}" >> /home/lance/registros.txt
        #become: no  # Garante que escreva no diretório do usuário lance sem erros de permissão de root
