---
- name: Up srsRAN server
  hosts: gnb
  
  vars:
    username: "lance"
    user_home: "/home/{{ username }}"
    essential_packages:
      - autoconf
      - automake
      - build-essential
      - ccache
      - cmake
      - cpufrequtils
      - doxygen
      - ethtool
      - g++
      - git
      - inetutils-tools
      - libboost-all-dev
      - libncurses5
      - libncurses5-dev
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libusb-dev
      - python3-dev
      - python3-mako
      - python3-numpy
      - python3-requests
      - python3-scipy
      - python3-setuptools
      - python3-ruamel.yaml
 
  tasks:
    - name: Registrar status de comissionamento
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') - Inicio de playbook" >> /home/lance/registros.txt
      become: yes

    - name: Install essential packages
      become: true
      package:
        name: "{{ essential_packages }}"
        state: present

    - name: Verificar se diretório UHD existe
      ansible.builtin.stat:
        path: "{{ user_home }}/uhd"
      register: uhd_dir

    - name: "Clone UHD repository"
      git:
        repo: https://github.com/EttusResearch/uhd.git
        dest: "{{ user_home }}/uhd"
        version: UHD-4.7
        update: no
      when: not uhd_dir.stat.exists

    - name: Permission for UHD
      become: true
      shell: |
        chmod 755 -R {{ user_home }}/uhd
      when: not uhd_dir.stat.exists

    - name: Ensure the UHD/host/build directory exists
      file:
        path: "{{ user_home }}/uhd/host/build"
        state: directory
      when: not uhd_dir.stat.exists

    - name: Cmake UHD
      command: cmake ../
      args:
        chdir: "{{ user_home }}/uhd/host/build"
        creates: "{{ user_home }}/uhd/host/build/CMakeCache.txt"
      when: not uhd_dir.stat.exists

    - name: Build UHD
      become: true
      shell: |
        make -j"$(nproc)"
        make install
        ldconfig
      args:
        chdir: "{{ user_home }}/uhd/host/build"
        creates: /usr/local/bin/uhd_find_devices
      when: not uhd_dir.stat.exists

    - name: USRP images downloader
      become: true
      ansible.builtin.command: /usr/local/lib/uhd/utils/uhd_images_downloader.py
      when: not uhd_dir.stat.exists

    - name: Permitir execução de nr-softmodem sem senha (via sudoers.d)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/nr_softmodem
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: {{ user_home }}/openairinterface5g/cmake_targets/ran_build/build/nr-softmodem"
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ler conteúdo de arquivo local e salvar em variável
      set_fact:
        open5gs_ip: "{{ lookup('file', '/tmp/ip-core.txt') }}"
      ignore_errors: true

    - name: Registrar status de comissionamento
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') - Comissionamento srsRAN Iniciado" >> /home/lance/registros.txt
      become: yes  
 
    - name: Ensure the {{ user_home }}/srsRAN/build directory exists
      ansible.builtin.stat:
        path: "{{ user_home }}/srsRAN/build"
      register: srsRAN_instalado
  
    - name: Clonar repositório srsRAN_Project na tag release_25_04
      ansible.builtin.git:
        repo: "https://github.com/srsran/srsRAN_Project.git"
        dest: "{{ user_home }}/srsRAN"
        version: "release_25_04"
        update: yes
      when: not srsRAN_instalado.stat.exists
    
    - name: Criar diretórios {{ user_home }}/srsRAN/build
      ansible.builtin.shell: mkdir {{ user_home }}/srsRAN/build
      args:
        executable: /bin/bash
      when: not srsRAN_instalado.stat.exists

    - name: Instalar dependências necessárias à compilação do srsRAN
      become: true
      apt:
        name:
        - cmake
        - make
        - gcc
        - g++
        - pkg-config
        - libfftw3-dev
        - libmbedtls-dev
        - libsctp-dev
        - libyaml-cpp-dev
        state: present
        update_cache: yes
      when: not srsRAN_instalado.stat.exists
    
    - name: Check if gnb binary exists
      ansible.builtin.stat:
        path: "{{ user_home }}/srsRAN/build/apps/gnb/gnb"
      register: gnb_binary_stat

    - name: Cmake srsRAN
      command: cmake ../
      args:
        chdir: "{{ user_home }}/srsRAN/build"
      when: not gnb_binary_stat.stat.exists

    - name: Build srsRAN
      become: true
      shell: |
        make -j"$(nproc)"
        make install
      args:
        chdir: "{{ user_home }}/srsRAN/build"
      when: not gnb_binary_stat.stat.exists

    - name: Permitir execução do binário gnb sem senha (via sudoers.d)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/gnb
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: {{ user_home }}/srsRAN/build/apps/gnb/gnb"
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
      when: not gnb_binary_stat.stat.exists
    
    - name: Template gnb_conf file
      template: 
        src: gnb.pacoteB.conf
        dest: "{{ user_home }}/srsRAN/utils/gnb.pacoteB.conf"
    
    - name: Template gnb_up_b210.sh file
      template: 
        src: gnb_up_b210.sh
        dest: "{{ user_home }}/srsRAN/utils/gnb_up_b210.sh"
    
    - name: Tornar gnb_up_b210.sh executável
      file:
        path: "{{ user_home }}/srsRAN/utils/gnb_up_b210.sh"
        mode: '0755'
        owner: "{{ ansible_user | default(omit) }}"
        group: "{{ ansible_user | default(omit) }}"
        state: file

    - name: Deploy docker-compose
      community.docker.docker_compose_v2:
        project_src: "{{ user_home }}/srsRAN/docker"
        files:
          - "docker-compose.yml"
        services:
          - grafana
          - influxdb
          - metrics-server
        state: present
      register: output

    - name: Execute tmux session
      command: "tmux new -d -s srsRAN_session \"cd ~/srsRAN/utils/ && ./gnb_up_b210.sh\""
   
    - name: Registrar status de comissionamento
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') - Comissionamento srsRAN Finalizado" >> /home/lance/registros.txt
      become: yes

        #- name: Registrar status de comissionamento
        #ansible.builtin.shell: |
        # echo "$(date '+%Y-%m-%d %H:%M:%S') - Comissionamento srsRAN Finalizado" >> {{ user_home }}/registros.txt(venv) 
