---
- name: Up srsRAN server
  hosts: gnb
  become: yes
  vars:
    # Defina o usuário explicitamente se o ansible_user falhar
    username: "lance"
    user_home: "/home/{{ username }}"

  tasks:
    - name: Registrar inicio
      ansible.builtin.shell: |
        echo "$(date '+%Y-%m-%d %H:%M:%S') - Iniciado" >> {{ user_home }}/registros.txt
  
    - name: Clonar repositório customizado do srsRAN
      ansible.builtin.git:
        repo: "https://github.com/leafaraujo/srsRAN.git"
        dest: "{{ user_home }}/srsRAN"
        version: "main" 
        update: yes
    
    - name: Adicionar repositório PPA do driver UHD (Ettus Research)
      apt_repository:
        repo: 'ppa:ettusresearch/uhd'
        state: present
        update_cache: yes

    - name: Instalar dependências necessárias à compilação do srsRAN
      become: true
      apt:
        name:
          - cmake
          - make
          - gcc
          - g++
          - pkg-config
          - libfftw3-dev
          - libmbedtls-dev
          - libsctp-dev
          - libyaml-cpp-dev
          - autoconf
          - automake
          - build-essential
          - ccache
          - cpufrequtils
          - doxygen
          - ethtool
          - git
          - inetutils-tools
          - libboost-all-dev
          - libncurses5
          - libncurses5-dev
          - libusb-1.0-0
          - libusb-1.0-0-dev
          - libusb-dev
          - python3-dev
          - python3-mako
          - python3-numpy
          - python3-requests
          - python3-scipy
          - python3-setuptools
          - python3-ruamel.yaml
          # Adicionei o driver UHD caso ainda não tenha
          - libuhd4.7.0
          - libuhd-dev
          - uhd-host
        state: present
        update_cache: yes
    
    - name: Garantir que o cache de bibliotecas (ldconfig) seja atualizado
      command: ldconfig
      changed_when: false # Isso apenas evita que o Ansible marque como "changed" toda vez

    - name: Baixar imagens do UHD (necessário para o B210)
      command: uhd_images_downloader
      register: uhd_dl
      changed_when: "'Images already installed' not in uhd_dl.stdout"
    
    - name: Check if gnb binary exists
      ansible.builtin.stat:
        path: "/home/lance/srsRAN/build/apps/gnb/gnb"
      register: gnb_binary_stat

    - name: Criar novo diretório de build
      file:
        path: "/home/lance/srsRAN/build"
        state: directory
        mode: '0755'
    
    - name: Cmake srsRAN
      command: cmake -DENABLE_WERROR=OFF ../
      args:
        chdir: "/home/lance/srsRAN/build"
      when: not gnb_binary_stat.stat.exists
    
    - name: Build srsRAN
      become: true
      shell: |
        make -j"$(nproc)"
        make install
      args:
        chdir: "/home/lance/srsRAN/build"
      when: not gnb_binary_stat.stat.exists

    - name: Permitir execução do binário gnb sem senha (via sudoers.d)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/gnb
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: {{ ansible_env.HOME }}/srsRAN/build/apps/gnb/gnb"
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
      become: yes
    
    
    - name: Tornar gnb_up_b210.sh executável
      file:
        path: "/home/lance/srsRAN/utils/gnb_up_b210.sh"
        mode: '0755'
        owner: "{{ ansible_user | default(omit) }}"
        group: "{{ ansible_user | default(omit) }}"
        state: file

    - name: Configurar Sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/gnb
        # Usamos o caminho absoluto para evitar erro de "~"
        line: "{{ username }} ALL=(ALL) NOPASSWD: {{ user_home }}/srsRAN/build/apps/gnb/gnb"
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ajustar permissões do script
      ansible.builtin.file:
        path: "{{ user_home }}/srsRAN/utils/gnb_up_b210.sh"
        mode: '0755'
        owner: "{{ username }}"
        group: "{{ username }}"
        state: file

    - name: Deploy docker-compose
      community.docker.docker_compose_v2:
        project_src: "/home/lance/srsRAN/docker"
        files:
          - "docker-compose.yml"
        services:
          - grafana
          - influxdb
          - metrics-server
        state: present

    - name: Execute tmux session
      # Usamos 'become: no' aqui para o tmux rodar no usuário 'lance' e não no root
      become: no
      ansible.builtin.shell: |
        tmux has-session -t srsRAN_session 2>/dev/null || \
        tmux new -d -s srsRAN_session "cd /home/lance/srsRAN/utils/ && ./gnb_up_b210.sh"
      args:
        executable: /bin/bash

    - name: Registrar fim
      ansible.builtin.shell: |
        echo "$(date '+%Y-%m-%d %H:%M:%S') - Finalizado" >> {{ user_home }}/registros.txt
